version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    command: pytest -q
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns

  langsmith:
    image: ghcr.io/langchain-ai/langsmith:latest
    ports:
      - "1984:1984"
